### PR TITLE
Fixes #5

### LINKED ISSUE #5: Unclickable navbar item shouldn't have hover feedback
A hover effect can give users a clear signal to see what's clickable. But in [tsugi2.css](https://github.com/tsugiproject/tsugi-static/blob/master/css/tsugi2.css#L426), the hover effect (border-bottom) is for the whole LI element, but only the anchor element inside the LI is clickable, even if we get hover effect when our mouse pointer enters the LI element, we don't get any change when we click it until we get the mouse inside the anchor element. So, the hover effect should be applied when the mouse enters the anchor element.

### PR DESCRIPTION
**Pull request by SarveshMD**
Fixes Issue #5

### CODE REVIEW

**Comment by csev** [comment]
Are you sure this is not trying to make the whole block change color?   I am just curious.   Where would I test this in the UI?

**Comment by SarveshMD** [comment]
To test this in the UI, just visit cc4e.com, open up developer tools in your browser (assuming you're on Google Chrome), you could go to the sources tab, expand the "static.tsugi.org" on the left sidebar, expand "css" and click tsugi2.css, scroll all the way down to line 426, select lines 426 through 430 and replace them with 
```css
.navbar-inverse .nav > li > a:hover,
.navbar-inverse .nav > li > a:focus,
.navbar-inverse .nav > li.active > a,
.navbar-inverse .nav > li.active > a:hover,
.navbar-inverse .nav > li.active > a:focus {
```
Now press control+s or cmd+s to save the file, and without refreshing the page, try hovering the items on the Navbar.
This should temporarily apply the changes I made to the site and you can verify if it is going to work the way you expect it to work. 
I don't know how to do this on firefox, but I think you should go to the style editor and find tsugi2.css and do the same.

**Comment by csev** [comment]
I tried that and it did not break anything - but also it did not seem to change anything - what am I looking for in the UI?  I move around and hover and with or without the change it seems to do the same - but I am guessing I am hovering the wrong place :)

**Comment by SarveshMD** [comment]
https://user-images.githubusercontent.com/76893756/130474271-96a7c650-8c33-4059-a440-64bc389fc279.mp4

As you can in the screencast, the hover effect is appearing even when the hovered item is un-clickable. When there is a hover effect for an element, we mean that the element is clickable or interactable. But the hover effect is appearing when the mouse enters the List Item element, but the list item element itself is not clickable, only the anchor element inside the List Item is clickable. So changing the hover effect from `li:hover a` to `li a:hover` and focus effect from `li:focus a` to `li a:focus` will fix this. That's what I have done in this pull request :)

**Comment by csev** [comment]
I could not see the video - but now I understand.   Thanks.

**Pull request merged**
